### PR TITLE
CSV/XML export unification and migration

### PR DESCRIPTION
**Pull request by simonporter007**
- Remove legacy plugin directories
- Create new unified plugin directory
- Copy over legacy scripts to legacy directory with the unified plugin
- migrate CSV and XML snippets to use the latest filters and actions

### CODE REVIEW

**Comment by tamarazuk** [comment]
@simonporter007 what do you think we organize the snippets in folders by format type (CSV vs. XML)?

**Comment by simonporter007** [comment]
@tamarazuk I have no particular feelings either way! csv/xml and then the filters that cover both in the main folder you mean?

**Comment by tamarazuk** [comment]
Yep, or at least updating the names as it's a bit tough to find snippets specific to XML right now. Users will typically be using one or the other I think

**Comment by simonporter007** [comment]
All updated tam, separate dirs and updated the dev docs.

**Pull request merged**
